services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8001:7196
      - 8003:5182
    networks:
      - targetFullstackApi

  angular:
    container_name: frontend
    build:
        context: ./frontend
        dockerfile: ./Dockerfile
    ports:
      - 8080:80
    networks:
      - targetFullstackApi
        
networks:
  targetFullstackApi: