# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "D:\\Target\\TargetFullstackAPI"
      dockerfile: "./api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "D:\\Target\\TargetFullstackAPI\\api:/app:rw"
    - "D:\\Target\\TargetFullstackAPI:/src:rw"
    - "C:\\Users\\Carlos\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
